### ISSUE TITLE
Link jobs together like `passed` but without a dependency on success.

### ISSUE THREAD

**Issue by srbry** [concourse/atc#105]
Connecting jobs together in a similar way to `passed` even if jobs have failed would be helpful, for example if you want to run some form of `post-test` despite an `action` job failing. You can currently easily trigger a new version to be omitted using an `ensure` with a `put` but it is not possible to draw it nicely in the GUI.

Maybe a small bar connected to the main `job` block could be used to display this while leaving the GUI Left to Right views clear.

**Comment by vito** [comment]
This feels like it'd be better accomplished by having an `ensure` in the job itself. I'm not a fan of coupling jobs together in this way; limiting it to resource progression keeps it conceptually simple imo.
