### ISSUE TITLE
Beacon error message not being interpolated properly

### ISSUE THREAD

**Issue by XenoPhex** [concourse/atc#113]
Noticed this error message not being formatted correctly:
```
beacon exited with error: failed to dial: failed to connect to TSA:%!(EXTRA *net.OpError=dial tcp <IP>:2222: i/o timeout)
```

**Comment by vito** [comment]
what

**Comment by XenoPhex** [comment]
Sorry, I hit enter by accident and it made the ticket before I finished typing the header...

**Comment by vito** [comment]
fixed by https://github.com/concourse/bin/commit/f382970c007726fff58aebf017501058162a1801
