### ISSUE TITLE
API for retrieving build history

### ISSUE THREAD

**Issue by csgavino** [concourse/atc#118]
Hi guys,

We have an internal app that shows the build state of different CIs and we’re looking to add support for Concourse. The problem is that Concourse doesn’t have a publicly documented API for retrieving the build history. I know that, that exists as you can use fly to retrieve it (fly -t example builds -j pipeline/jobs).

Are there any plans of adding/exposing the API that fly uses or are there any alternatives that I can use to retrieve it?

**Comment by cdutra** [comment]
Hi Carlos,

you can use the go-concourse lib: https://github.com/concourse/go-concourse
Fly uses this lib to communicate with ATC.

**Comment by vito** [comment]
consolidating into https://github.com/concourse/atc/issues/80
