### ISSUE TITLE
ATC continues to log errors for retired workers

### ISSUE THREAD

**Issue by jcderr** [concourse/atc#119]
I scale-out my workers during non-office hours to save on EC2 costs. ATC appears to continue to reference these long dead workers.

As a result, my logs blow up every few moments with hundreds of lines like this:

    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520518303","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-200-186"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520532131","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-14"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520547152","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-200-164"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520560741","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-184"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520573854","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-148"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520587444","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-83"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520601034","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-200-77"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520614386","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-153"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520629406","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-200-199"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520642757","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-156"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520663261","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-151"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520679951","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-200-70"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520694256","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-49"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520709038","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-216"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520723343","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-69"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520744562","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-12"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520759344","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-99"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520777464","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-201-54"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520794392","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-200-24"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520808935","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-200-73"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520822763","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-200-62"}}
    Sep 28 19:52:01 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092321.520838261","source":"atc","message":"atc.baggage-collector.could-not-locate-worker","log_level":1,"data":{"session":"16","worker-id":"ip-10-0-200-71"}}
    Sep 28 19:52:10 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092330.037646294","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.100.132:41521","session":"2","type":"keepalive"}}
    Sep 28 19:52:11 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092331.322051764","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.101.104:3144","session":"1","type":"keepalive"}}
    Sep 28 19:52:11 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092331.439638376","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.100.99:38935","session":"3","type":"keepalive"}}
    Sep 28 19:52:15 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092335.037634134","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.100.132:41521","session":"2","type":"keepalive"}}
    Sep 28 19:52:16 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092336.323278189","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.101.104:3144","session":"1","type":"keepalive"}}
    Sep 28 19:52:16 ip-10-0-101-230 concourse[3582]: {"timestamp":"1475092336.439640045","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"10.0.100.99:38935","session":"3","type":"keepalive"}}

However, the `workers` table in postgres only lists the currently extant workers.

**Comment by philk** [comment]
Same issue here, we're trying to autoscale our nodes and they run in k8s pods which works reasonably well except for this issue. It would also be nice for us to be able to drain a node (or have a node report itself as going away) so ATC doesn't get confused trying to schedule jobs.

**Comment by vito** [comment]
This'll be fixed by http://github.com/concourse/concourse/issues/629
