### ISSUE TITLE
internal TLS certificate verification errors for valid certificate

### ISSUE THREAD

**Issue by craigfurman** [concourse/atc#123]
We deployed concourse 2.2.0 with `tls_cert` and `tls_key` set. The certificate was signed by a real root CA and valid for our domain. Our `external_url` contains the non-standard HTTPS port: `https://services-enablement-gcp.ci.cf-app.com:4443`. This is our first time deploying concourse without an SSL-terminating reverse proxy (which we have omitted in this case because, reasons).

Making any request to the TLS-secured port results in an HTTP 500, and we see the following log message:

```
{"timestamp":"1475753423.812040091","source":"atc","message":"atc.index.failed-to-list-pipelines","log_level":2,"data":{"error":"Get https://services-enablement-gcp.ci.cf-app.com:4443/api/v1/pipelines: x509: certificate signed by unknown authority","session":"117"}}
```

When we re-deployed with `allow_self_signed_certificates: true`, we were able to securely access concourse, with TLS verification enabled on our client (the cert is valid). It looks like some internal code is not trusting the system certs.

On a slightly unrelated note, would it be possible to [grant the atc executable the Linux capability to bind low ports](http://stackoverflow.com/questions/413807/is-there-a-way-for-non-root-processes-to-bind-to-privileged-ports-1024-on-l)? That way we could use standard ports 80 and 443 without running ATC as root in bosh.

cc @jamesjoshuahill

**Comment by vito** [comment]
The latter part is already supported:

https://github.com/concourse/concourse/blob/master/jobs/atc/templates/atc_ctl.erb#L70

**Comment by craigfurman** [comment]
@vito indeed it is, that's pretty awesome. Original issue is still a problem though. There's a similar issue with fly that I'm about to raise on that repo

**Comment by vito** [comment]
This'll actually go away in the next release anyway, since we no longer have the ATC talking to itself.
