### ISSUE TITLE
Job 'builds' displays incorrectly.

### ISSUE THREAD

**Issue by mmb** [concourse/atc#124]
On Concourse 2.2.1, viewing a job improperly displays 'builds' on top of the first job number

![screen shot 2016-10-10 at 11 29 38 am](https://cloud.githubusercontent.com/assets/24275/19246888/5fffc568-8edd-11e6-82c6-c790738e10d0.png)

**Comment by vito** [comment]
Fixed already but haven't released yet. Thanks for the issue though!
