### ISSUE TITLE
Job structure briefly displayed for "public" pipelines

### ISSUE THREAD

**Issue by mtekel** [concourse/atc#126]
When you set pipeline as public, concourse makes high level diagram visible, but it should hide build history and logs (https://concourse.ci/teams.html#exposing). I have noticed that for a brief time, job structure is also exposed (see the attached gif and picture split from it) including the versions of the resources used. Looks like this was not intended, as it is immediately hidden. Concourse version 2.2.1.

Note that in this mode, resource versions are also visible. This can perhaps leak some information. Maybe this should be hidden as well?
![concourse_jog_details](https://cloud.githubusercontent.com/assets/483891/19523741/594610d2-9613-11e6-9da8-ca1ab55627ff.gif)
![concourse-job-contents](https://cloud.githubusercontent.com/assets/483891/19523742/594648a4-9613-11e6-8ea7-7320f16c2380.gif)

**Comment by vito** [comment]
Yeah that's a bit glitchy but not a security thing; resource versions and metadata are publicly viewable. (You can see them on the resource page too.) Which we used to state in the docs but I think that must've gotten lost in reshuffling after Teams came in.

**Comment by mtekel** [comment]
OK, I guess it's not a bug then. But it looks suspicious. Almost like "public" functionality is just something on top of normal view that hides things and sometimes it's not fast enough...
