### ISSUE TITLE
is there support for custom base url path?

### ISSUE THREAD

**Issue by navicore** [concourse/atc#127]
I'd like to use a different (non-root) base URL on the ATC WEB to use path-only LB forwarding.  

Is it possible to globally set baseUrl with a path?

I've tried:
```
"CONCOURSE_EXTERNAL_URL": "https://my.domain.com/ci"
```
But concourse web is looking for `/public` instead of `/ci/public`.

Thx

**Comment by vito** [comment]
There's no support for this at the moment.

**Comment by G2Jose** [comment]
This would be an amazing feature to have!

**Comment by edysli** [comment]
> There's no support for this at the moment.

@vito Then at least document this, because naming that parameter "URL" implies that a base path is supported.
