### ISSUE TITLE
favicon retains green/red color after navigating back to pipeline in chrome

### ISSUE THREAD

**Issue by craigfurman** [concourse/atc#129]
Really minor UI bug:

Using concourse 2.3.1

1. go to a finished build run results page (in Google Chrome)
1. favicon is now red/green if build failed/passed, as expected
1. navigate to home, or to a pipeline
1. favicon retains color rather than being black
1. refresh page, favicon is black as expected

not sure if this happens to running jobs as well as finished ones, but it might.

This basically doesn't matter, we just figured we'd let you know anyway. Worth it for lightning-fast new web UI

cc @jamesjoshuahill

**Comment by vito** [comment]
Fix already, will be in 2.4 - thanks!
