### ISSUE TITLE
Input and output paths cannot be absolute

### ISSUE THREAD

**Issue by saliceti** [concourse/atc#131]
Using absolute paths would be useful and would mimc the behaviour of volumes in docker.
But paths are forcefully made relative to the working directory by design: [outputs](https://github.com/concourse/atc/blob/102e8856983a548797f5c55ebe4f2deea7540ef2/exec/task_step.go#L737) and [inputs](https://github.com/concourse/atc/blob/102e8856983a548797f5c55ebe4f2deea7540ef2/exec/task_step.go#L596)

However the documentation for [inputs](https://concourse.ci/running-tasks.html#inputs) and [outputs](https://concourse.ci/running-tasks.html#outputs) doesn't say the path cannot be absolute.

Ideally we want to be able to use absolute paths, but if it is not possible, we should at least fix the doc.

**Comment by chendrix** [comment]
We explicitly *do not* want input and output paths to be absolute. I agree this could be better messaged via documentation. Despite closing this, I'm tagging your tracker issue with `docs` so we can track it as part of a larger epic on Documentation.
