### ISSUE TITLE
Default pipeline view should show all jobs when using groups

### ISSUE THREAD

**Issue by TimJones** [concourse/atc#135]
Currently, selecting a pipeline from the sidebar shows all jobs only if the pipeline has no groups configured.

If the pipeline has groups, the first group is shown even though it is not highlighted in the group bar. This means I could loose visibility of jobs in a pipeline that are not part of any specific group.

I propose that the default view for a pipeline (<concourse URL>/teams/<team>/pipelines/<pipeline>) should always display all jobs in the pipeline. This way the 'home' icon/link shows the entire pipeline, and the groups bar/list shows only jobs configured for that group.

**Comment by vito** [comment]
The first group is highlighted for me.

**Comment by vito** [comment]
Actually just gonna close this in favor of https://github.com/concourse/concourse/issues/469 - I don't think we should just change the behavior at this point. There could be a more interesting discussion in the other issue.

**Comment by TimJones** [comment]
@vito Reading concourse/concourse#469 it seems a much better solution. Thanks!
