### ISSUE TITLE
ATC web ui no showing job information

### ISSUE THREAD

**Issue by ese** [concourse/atc#143]
I have a job that doesn't show any log or steps in the web-ui but if you use `fly  watch` all works fine.
This is the log from browser console
```
elm.min.js?id=4be91db…:1 
failed to fetch plan: UnexpectedPayload "Expecting an object at _.inputs[0].version but instead got: null": ({ build = { id = 1263, url = "/teams/main/pipelines/qa-client/jobs/run-end2end-tests/builds/71", name = "71", job = Just { teamName = "main", pipelineName = "qa-client", jobName = "run-end2end-tests" }, status = BuildStatusSucceeded, duration = { startedAt = Just <Thu Dec 01 2016 13:28:14 GMT+0100 (CET)>, finishedAt = Just <Thu Dec 01 2016 13:30:03 GMT+0100 (CET)> }, reapTime = Nothing }, steps = Nothing, errors = Nothing, state = StepsLoading, events = { type = "node", branches = [] }, eventSourceOpened = False },{ type = "node", branches = [] },OutNoop)
```

I am running concourse 2.5.0 in docker containers

**Comment by chendrix** [comment]
Hi there @ese is this still a problem you're seeing?

Have you tried asking in our [slack channel](https://slack.concourse.ci) or on [stackoverflow](http://stackoverflow.com/questions/tagged/concourse%3E)?

**Comment by ese** [comment]
We deleted and recreate the pipeline and we are unable to reproduce it so we can closed this. Thanks

**Comment by literatesnow** [comment]
@ese This error means that there is a [resource](https://concourse.ci/implementing-resources.html) in your pipeline which isn't returning a version. Ensure that ``/opt/resource/in`` and ``/opt/resrouce/out``'s result contains version in the JSON.

For example:

```bash
#!/bin/sh

echo '{"version":{"ref":"none"}}'
```
