### ISSUE TITLE
ATC not setting necessary security related HTTP headers

### ISSUE THREAD

**Issue by jbarnicle** [concourse/atc#144]
In order to be in compliance with best practice security guidelines, ATC should set the following HTTP headers

- ` X-XSS-Protection: 1; mode=block`
- `cache-Control: no-cache, no-store, must-revalidate, private`
- `pragma: no-cache`

**Comment by vito** [comment]
Got a link to something that documents these as standard and why? Those sound like they'd change user-facing behavior in particular ways (`no-cache` especially), and shouldn't just be added for the sake of it.

**Comment by jbarnicle** [comment]
@vito Our particular need stems from a certification requirement being place on our system by [NIST](https://web.nvd.nist.gov/view/800-53/Rev4/control?controlName=CM-6).  I understand that not everyone would want / need these headers set - so I would amend the issue to state that there should be a configuration point to add response headers.

**Comment by cnelson** [comment]
Agreed that we shouldn't set the cache control headers for everyone, but [X-XSS-Protection: 1; mode=block](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) and [X-Content-Type-Options: nosniff](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options) (not mentioned in the original request, but important) are useful and shouldn't impact user-facing behavior.

There's a bit more info in the [Mozilla Security Guidelines](https://wiki.mozilla.org/Security/Guidelines/Web_Security) and @jmcarp is having a discussion about adding these headers to Grafana using https://github.com/unrolled/secure in https://github.com/grafana/grafana/issues/6820 which may be useful appraoch for ATC as well.

**Comment by chendrix** [comment]
Hi all, this will be fixed and delivered as part of 2.7.1 https://github.com/concourse/atc/compare/5b04c1fa5a37312291b3dc1f79a130f590264fad...3d3252914b3b5ab52381302cd28922c315be5691#diff-20bd1a6996c96469214da01b9a7aae78
