### ISSUE TITLE
Error saying no workers satisfying: resource type 'docker-image', platform 'linux'

### ISSUE THREAD

**Issue by G2Jose** [concourse/atc#146]
I just followed the Hello, World! guide to concourse on https://concourse.ci/hello-world.html. I'm running MacOS Sierra. 

On running `fly -t lite set-pipeline -p hello-world -c hello.yml` and navigating to `http://localhost:8080`, I see a message saying 

> no workers satisfying: resource type 'docker-image', platform 'linux'
>available workers: 
> - platform 'darwin'

Prior to this, I also installed the standalone binary and followed all steps on https://concourse.ci/binaries.html

Anyone else have the same issue?

**Comment by vito** [comment]
Until there are OS X implementations of various resource types, you'll need to have one Linux worker around for running resource workloads. Then the fetching will be performed on that worker, and the fetched bits will be streamed over to the Darwin worker.
