### ISSUE TITLE
Building pulsing is buggy on concourse 2.5.1

### ISSUE THREAD

**Issue by benmoss** [concourse/atc#148]
This screenshot actually makes it look tame in comparison to the frequency this thing is pulsing on my screen. It seems like it only manifests itself at certain zoom levels.

http://whatsmybrowser.org/b/M1ED8RH

![concourse-builds](https://cloud.githubusercontent.com/assets/239754/21503478/c6cad96a-cc25-11e6-9d95-29ca0affcf0e.gif)

**Comment by vito** [comment]
This is some sort of Chrome regression; we haven't touched that part of the UI in ages. Plotting to come up with a new indicator anyway.

**Comment by roobert** [comment]
I'd also like to add that when we have lots of parallel jobs there's quite a bit of overlap, here's a screenshot (oddly, not showing the corruption although it is occurring in the browser) -- thought I'd mention this here as it's related to the indicator:

![concourse](https://cloud.githubusercontent.com/assets/226654/21892341/403abcac-d8ce-11e6-92ed-427c51ae343a.png)

**Comment by timatooth** [comment]
Has anyone managed to trace down what changed between the chrome versions to introduce this top try fix it? The pulsing looks like it's having a serious epileptic moment!

**Comment by zachgersh** [comment]
@vito - you think it would be enough if we just swapped the radiating animation for actually making the whole job box pulse? if it grew by a significant amount it would probably be noticeable.

**Comment by vito** [comment]
Moved to concourse/concourse#1127
