### ISSUE TITLE
Newest garden-linux-release wants a user

### ISSUE THREAD

**Issue by SchwarzM** [concourse/atc#19]
Hi, 
i've recently deployed the newest garden-linux-release and found that atc won't specify a user resulting in:
error":"linux_container: Run: A User for the process to run as must be specified. ...."

https://github.com/concourse/atc/blob/master/exec/task_step.go#L144 does not specify any user so that part is right. 

Anything i am missing here ?

cya
M.Schwarz

**Comment by SchwarzM** [comment]
Related garden spec:
https://github.com/cloudfoundry-incubator/garden/blob/master/container.go#L155

**Comment by vito** [comment]
Be sure to use the release we've shipped alongside ours, not the latest. Right now, 0.56 works with 0.205 of Garden, as can be seen here:

https://github.com/concourse/concourse/releases/tag/v0.56.0

We're working on upgrading but it's a bit of work. The story tracking it is here:

https://www.pivotaltracker.com/story/show/96394304

**Comment by vito** [comment]
This should be resolved now that we've upgraded our dependency and are once again continuously integrating with Garden Linux.
