### ISSUE TITLE
Allow sidebar to be adjustable

### ISSUE THREAD

**Issue by lnguyen** [concourse/atc#27]
![rdpg-boshrelease_-_concourse](https://cloud.githubusercontent.com/assets/928524/9094189/6de292ae-3b7e-11e5-95b9-fcd0b4d81f65.png)

**Comment by thewoolleyman** [comment]
Hi - we also have the problem of half our pipeline names being cut off (because we namespace them by prefixing the repo/project name at the beginning of the pipeline).

Can we at least increase the fixed width to 400 or 450px?

**Comment by vito** [comment]
Moved to concourse/concourse#1130
