### ISSUE TITLE
Deadlock detected acquring build tracking lease

### ISSUE THREAD

**Issue by ry4n1m3** [concourse/atc#34]
```json
{"timestamp":"1444779382.015635014","source":"atc","message":"atc.build-tracker.track.failed-to-get-lease","log_level":2,"data":{"build":8302,"error":"pq: deadlock detected","session":"5.139138"}}
```

possibly related to memory contention on our vSphere cluster - @vito 

plenty of other weirdness:

![screen shot 2015-10-13 at 5 56 03 pm](https://cloud.githubusercontent.com/assets/384771/10472300/b6e31254-71d3-11e5-96d4-01bd0378d6b4.png)
![screen shot 2015-10-13 at 5 55 42 pm](https://cloud.githubusercontent.com/assets/384771/10472299/b6e29676-71d3-11e5-9995-cafe16b50586.png)
![screen shot 2015-10-13 at 5 55 33 pm](https://cloud.githubusercontent.com/assets/384771/10472296/b6e1efb4-71d3-11e5-84af-a32ca2961412.png)
![screen shot 2015-10-13 at 5 55 56 pm](https://cloud.githubusercontent.com/assets/384771/10472297/b6e21746-71d3-11e5-93f2-6ec428b84518.png)
![screen shot 2015-10-13 at 5 55 38 pm](https://cloud.githubusercontent.com/assets/384771/10472298/b6e23b40-71d3-11e5-9940-8ebee8ff2cad.png)
![screen shot 2015-10-13 at 5 55 48 pm](https://cloud.githubusercontent.com/assets/384771/10472301/b6e3a3ae-71d3-11e5-8068-3421ec7fc6d5.png)

**Comment by vito** [comment]
Gonna attribute these to the environment falling over after running out of memory; some of those screenshots showed things that should be downright impossible.
