### ISSUE TITLE
build pages timing out on (new elm-based) UI

### ISSUE THREAD

**Issue by thewoolleyman** [concourse/atc#40]
This is on 0.70.1-rc.4

Our build pages for complex builds (many colored dots/lots of output) are timing out.  Attached are screenshots of network timings from two different loads.  The first 'events' entry takes ~43 seconds, and the second one times out at about a minute or so.

![screen shot 2015-12-29 at 10 55 46 am](https://cloud.githubusercontent.com/assets/158/12039216/af76cb08-ae1b-11e5-9d78-fb3402b42bf8.png)
![screen shot 2015-12-29 at 10 54 04 am](https://cloud.githubusercontent.com/assets/158/12039217/af787084-ae1b-11e5-9bb4-f0bf3b5170ec.png)

**Comment by thewoolleyman** [comment]
FYI, this is intermittent.

Discussed in concourseci slack, was suggested this might be a DB performance issue; our db is postgres on a t2.medium AWS instance which is burst.  Will try moving to a constant performance instance and see if this issue goes away.

**Comment by vito** [comment]
We've optimized the build UI enough to be faster than it was before Elm, just haven't shipped yet. This particular issue I think was due to the slow DB instance type.
