### ISSUE TITLE
API authentication without using basic auth

### ISSUE THREAD

**Issue by mmb** [concourse/atc#42]
It would be nice to be able to authenticate to the Concourse API in scripts without using basic auth. The current OAuth workflow can only happen in a browser that is logged into Github.

It was mentioned in Slack that there could be another auth type like personal access tokens. There are also other OAuth flows that might make sense.

**Comment by xoebus** [comment]
Yeah, we're thinking about this.

Out of interest, what kind of script would you like to write?

**Comment by mmb** [comment]
Our original requirement was to send notifications to our PM when a build had failed a certain number of consecutive times.

We were able to get recent build statuses unauthenticated but after #41 that won't work any more.

If there are any features planned for events/notifications that would satisfy our requirements too.

**Comment by pcf-releng** [comment]
@xoebus we have a similar app on CF Release Engineering, which sends us slack notifications when our builds fail. We would also like to have this feature so we can turn off basic auth. Was hoping to use https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app to create a token on behalf of concourse but we're open to another solution as well. Will follow this issue to see what happens. Thanks!

**Comment by rmasand** [comment]
@xoebus we have a similar app on CF Release Engineering, which sends us slack notifications when our builds fail. We would also like to have this feature so we can turn off basic auth. Was hoping to use https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app to create a token on behalf of concourse but we're open to another solution as well. Will follow this issue to see what happens. Thanks!

**Comment by vito** [comment]
This will be needed for https://github.com/concourse/concourse/issues/331 - I'm thinking it could just be implemented as CRUD of access tokens via the API. The tokens would have the same permissions as the token used to create them. They could then be embedded in the URL as `?access_token=<token>`, to support hooks (the aforementioned issue). It could also be added to Fly as a flag.

**Comment by aclevername** [comment]
Any update on this? +1

**Comment by vito** [comment]
Moved to concourse/concourse#1116
