### ISSUE TITLE
Allow github oauth with github enterprise

### ISSUE THREAD

**Issue by aequitas** [concourse/atc#49]
Currently the oauth endpoint is hardcoded to `github.com`: https://github.com/concourse/atc/blob/master/auth/github/provider.go#L35

Would be nice if it could be set to a internal GE instance for authentication.

**Comment by superbeeny** [comment]
+1

**Comment by aequitas** [comment]
https://github.com/concourse/atc/pull/60

**Comment by vito** [comment]
done via the aforementioned PR
