### ISSUE TITLE
how to use github webhooks for triggering

### ISSUE THREAD

**Issue by weberstephanhd** [concourse/atc#54]
Hi,

is it possible or planned that github webhooks can be used instead of polling for new commits on git repos? Our pipelines' pollings create way too much traffic on certain github repos whose content changes seldomly. 

Best regards, Stephan Weber

**Comment by superbeeny** [comment]
+1

**Comment by macropin** [comment]
I believe there needs to be support for webhooks as triggers for all pipelines/jobs.

**Comment by vito** [comment]
Closing this to consolidate with https://github.com/concourse/concourse/issues/331 - we'll be picking this up soon!
