### ISSUE TITLE
Resource icons

### ISSUE THREAD

**Issue by aequitas** [concourse/atc#64]
It would be nice to have icons associated with resources. This way it is easy at a glance to see which type of resource is being in/outputted. And it prevents resource names with the type included.

**Comment by aequitas** [comment]
I think the best way to implement this is using some config options for resources. Since a certain resource type (eg: s3) might have different kind of resources (tarball, python wheel, debian package, etc), it would make sense to bind the icons to strictly to resource_types.

This way the user can customize the icons to the actual content of the pipeline. Currently i'm using a method of prefixing a resource with 'type:' but i think its an ugly and verbose solution.

**Comment by vito** [comment]
This could maybe be something returned by the `info` script described in https://github.com/concourse/concourse/issues/534 ?

**Comment by aequitas** [comment]
Yes/no. I think for resource type specific icons it would definitely work. But if you want to upload multiple different artifacts (.deb, .rpm,. tgz, etc) to the same resource type there would be no way to make the distinction.

**Comment by vito** [comment]
Moved to concourse/concourse#1120
