### ISSUE TITLE
Horizontal scrolling is broken on build views

### ISSUE THREAD

**Issue by benmoss** [concourse/atc#68]
When my build view has a long line that make the output scroll horizontally, I can't scroll to the right. The Javascript on the page seems to keep pushing it back to the left every time I hit the right arrow key.

https://main.bosh-ci.cf-app.com/pipelines/bosh-agent-windows/jobs/test-vsphere-stemcell/builds/38 is an example of this. You'll have to narrow the window to see this bug. Only tried Chrome 49.0.2623.87.

**Comment by vito** [comment]
This should be fixed with 1.0.
