### ISSUE TITLE
Support for non-container workloads

### ISSUE THREAD

**Issue by gtirloni** [concourse/atc#69]
It would be nice if Concourse could run tests outside containers (which seem the main focus right now).

As an example, we have a Jenkins server that connects to a slave and starts a custom-built Vagrant VM that runs tests on GNOME 3 and other desktop environments (e.g. Windows). Sometimes these tests must be able to perform certain things that only exist in a Virtual Machine or even a proper Desktop computer (e.g. audio).

Since Concourse relies on Garden heavily, and Garden seems to work exclusively with workers, it's not clear how to migrate our CI pipeline to Concourse.

**Comment by gtirloni** [comment]
Just realized I opened this issue in the 'atc' repository. If it should be closed and opened again in the 'concourse' repository, please let me know.

**Comment by Tankanow** [comment]
+1
Concourse truly seems like the best CD tool out there, unfortunately, I too don't see a clear path to migrate to concourse without access directly to the worker OS. We have moved heavily to `docker-compose`, providing a nice parity between local development and cluster deployment. I'm sure I'm missing something here but I don't see a clear way in concourse for `docker-compose`, using `docker` natively, or for testing an application packaged inside a docker image, which I think should mean starting a container from that image and testing the interface. Like most, we maintain parity with `packer` so our platforms hosting workers are already reproducible environments mitigating the need for tasks to run inside containers.

**Comment by vito** [comment]
This is already abstracted away by Garden. You're free to use a no-op backend like [Houdini](https://github.com/vito/houdini) instead of a "real" backend.
