### ISSUE TITLE
Support for Pipeline Group Separators

### ISSUE THREAD

**Issue by zachgersh** [concourse/atc#71]
When you get to having a lot of pipelines - grouping them because a way to draw your eye directly to the section of the side panel your pipeline resides in.

We've done this in a hacky way and it looks like this:

![screen shot 2016-03-31 at 11 29 28 am](https://cloud.githubusercontent.com/assets/689411/14186563/d81085ac-f733-11e5-97c1-1bb9855afaa2.png)

Would be nice to officially support this so it doesn't have to be a paused blank pipeline.

**Comment by vito** [comment]
Closing this in favor of https://github.com/concourse/concourse/issues/532
