### ISSUE TITLE
Support runtime configuration passing between out/in on resources

### ISSUE THREAD

**Issue by LinuxBozo** [concourse/atc#72]
There are times where you want to specify runtime configuration during the `out` phase of a resource. This configuration typically happens in the `params`, rather than the resource's `source`. Due to the way resources perform `in` directly after `out`, this runtime configuration from the `params` is lost.

One example in particular is the [`bosh-deployment` resource](https://github.com/concourse/bosh-deployment-resource), where the BOSH target can be specified with `target_file` in the `params`. Because this runtime configuration is scoped only to the `out`, there was a decision made to include the `target` from the `target_file` in the `version` output so it is available to the impending `in`. This seems counter to the intent of what makes up a `version`. Instead, I believe it makes sense to either pass along the `params` (or as a new bit called `runtime`) as well as `version` between these actions. This will allow the passing of the configuration separately from the `version` for less confusion.

**Comment by vito** [comment]
Consolidating this into https://github.com/concourse/concourse/issues/534 - may want to read up on there and see if any of those things satisfy this need. Also https://github.com/concourse/concourse/issues/684
