### ISSUE TITLE
Get error "could not read file from tar"

### ISSUE THREAD

**Issue by mschaaf** [concourse/atc#78]
I setted up concourse on AWS with the standalone binary way (http://concourse.ci/binaries.html) and I am getting the following error 'could not read file from tar' on executing my pipeline.

If I run the same pipeline against a concourse setup within a local VM with vagrant it runs.

This is my configured image resource:

```
image_resource:
         type: docker-image
         source: {repository: ubuntu}
```

There is no more error message in the logs and from the source code it seems that the original error is hidden.

What is the cause of the error so that I can use concourse?

**Comment by james-thimont-bcgdv** [comment]
I have the same problem running it on kubernetes

**Comment by etiennetremel** [comment]
Any update about this issue? I'm also facing the same problem on Kubernetes.

**Comment by james-thimont-bcgdv** [comment]
@etiennetremel I ran it on a kubernetes cluster on aws running a linux version with a kernel that was too old.  Should be 3.19 at least.
It works fine on a cluster running ubuntu wily

**Comment by etiennetremel** [comment]
@james-thimont-bcgdv unfortunately I'm using GKE/GCE, and their container vm doesn't seem to suppose this version of the kernel. I also check their container vm gci-dev-52-8244-0-0, and it is using 3.18.. 
Not sure if this is related but I checked linux garden and it seems to support Ubuntu LTS which is 3.16.

**Comment by vito** [comment]
You need kernel 3.19 and above, as mentioned in the [Prerequisites](https://concourse.ci/binaries.html#prerequisites). Ubuntu 14.04 has this kernel available via `apt`. We'll soon support Ubuntu 16.04 and many other distributions with Concourse 1.3+, but the kernel 3.19+ requirement remains.

**Comment by mschaaf** [comment]
The AWS instance I use runs Ubuntu 14.04 but with kernel 3.13. I try to upgrade and report back if this helped. One important improvement I can see, if this fixes the issue, is a better error message.
