### ISSUE TITLE
atc crashes with "too many open files"

### ISSUE THREAD

**Issue by jochenehret** [concourse/atc#79]
Hi,

we are running Concourse 0.74 and our atc jobs on the "web" nodes are crashing often with:

failed to enable connection keepalive: file tcp 10.1.6.0:33296->10.1.6.12:7777: fcntl: too many open files
failed to enable connection keepalive: file tcp 10.1.6.0:33297->10.1.6.12:7777: fcntl: too many open files
failed to enable connection keepalive: file tcp 10.1.6.0:33299->10.1.6.12:7777: fcntl: too many open files
failed to enable connection keepalive: file tcp 10.1.6.0:33303->10.1.6.12:7777: fcntl: too many open files
failed to enable connection keepalive: file tcp 10.1.6.0:33314->10.1.6.12:7777: fcntl: too many open files
failed to enable connection keepalive: file tcp 10.1.6.0:35453->10.1.6.12:7777: fcntl: too many open files
failed to enable connection keepalive: file tcp 10.1.6.0:35455->10.1.6.12:7777: fcntl: too many open files
failed to enable connection keepalive: file tcp 10.1.6.0:35456->10.1.6.12:7777: fcntl: too many open files
failed to enable connection keepalive: file tcp 10.1.6.0:35457->10.1.6.12:7777: fcntl: too many open files
failed to enable connection keepalive: file tcp 10.1.6.0:35458->10.1.6.12:7777: fcntl: too many open files

As a workaround, we call "monit restart atc". Do you know the root cause of this problem? Please tell us if you need more system information for analysis.

Thanks and Best Regards,

  Jochen.

**Comment by vito** [comment]
it's been quite a while since this was opened and there's little hope of us diagnosing the exact issue, so I'll just close this.

this should at least get better with in-flight work to redo how we manage containers and volumes, as it looks like it ran out of FDs talking to Garden

**Comment by cdutra** [comment]
Hey @vito,

Just as a datapoint, we'd like to let you know that this is also happening on BOSH CPI's Concourse approximately every 2 days and we fix it by `monit restart all`. Typical entry in `/var/vcap/sys/log/atc/atc.stderr.log`

```
2016/11/03 00:51:31 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 20ms
2016/11/03 00:52:01 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 5ms
2016/11/03 00:52:01 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 10ms
2016/11/03 00:52:01 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 20ms
2016/11/03 00:52:01 http: Accept error: accept tcp [::]:8080: accept4: too many open files; retrying in 40ms
```

**Comment by cunnie** [comment]
We created a release that fixes this issue by changing the ulimit open files for monit which atc inherits.
Here's the [release](https://github.com/pivotal-cf/ulimit-release)
