### ISSUE TITLE
As a Concourse user, I would like Concourse to fail validation of my configuration if there are unused resources

### ISSUE THREAD

**Issue by mmb** [concourse/atc#86]
When I run set-pipeline with a pipeline config that has resources defined that are not used in any jobs I would l like it to fail validation.

In the same vein as golang refusing to compile with unused imports and variables, this can reveal bugs, reduce cruft and make it easier to clean up dependencies of jobs that have been removed.

Willing to send PR.

**Comment by mmb** [comment]
I wrote some code to generate warnings for unused resources, but they show up in fly as deprecation warnings. It could be easily changed to generate errors.

@vito Is there any version of this that you would accept a PR for?

**Comment by vito** [comment]
Yeah, I like the idea of having that fail validation. Thanks for working on this!

**Comment by vito** [comment]
closing this since we merged the PR
