### ISSUE TITLE
High CPU usage in Chrome with large number of jobs displayed

### ISSUE THREAD

**Issue by ematpl** [concourse/atc#88]
The Diego team has a substantial number of build jobs in its pipeline. When I have a tab open that displays a lot of them, that tab consistently uses 100% CPU or more (screenshots attached). As a result, I typically have to kill that tab in the Chrome Task Manager to conserve battery power on my laptop and to retain enough CPU for the system to perform well, negating the benefit of having the pipeline available continually in a browser tab for quick reference.

Concourse version: 1.3.0
Chrome version: 51.0.2704.84 (64-bit)
OS: Mac OS X 10.10.5
CPU hardware: 2.6 GHz Intel Core i7, 4 cores (hyper-threaded to 8)

Please let me know if there is more information I can provide that would be helpful.

Thanks,
Eric

<img width="1054" alt="chrome-task-manager" src="https://cloud.githubusercontent.com/assets/5836757/16102824/2b20959a-3328-11e6-9378-6d18b9cf2906.png">
<img width="1280" alt="concourse-diego-pipeline-1 3 0" src="https://cloud.githubusercontent.com/assets/5836757/16102823/2a29d08e-3328-11e6-968a-2d11990dec49.png">

**Comment by vito** [comment]
@ematpl Has this gotten better with recent versions? We only redraw if the data set is different now, which should help.

**Comment by ematpl** [comment]
Thanks, @vito, I'll check and report back. Diego's CI is currently on Concourse v2.2.0.

**Comment by ematpl** [comment]
It seems improved, but still not great:

- When the window is not minimized, it still consumes about 50% to 85% of one core, regardless of whether it's in the foreground or not.
- When the window is minimized, it drops to ~0% CPU usage pretty much immediately.

Chrome version is now 53.0.2785.143; OS X version and hardware are the same.

Thanks again,
Eric

<img width="1057" alt="screen shot 2016-10-09 at 12 12 22 pm" src="https://cloud.githubusercontent.com/assets/5836757/19223005/21011e98-8e1a-11e6-8883-757ed6559690.png">

**Comment by vito** [comment]
Looks like it's from the running animations. Deleted those elements and CSS and CPU usage went way down.

**Comment by Eulerizeit** [comment]
This has seemingly gotten worse on 2.5.0. CPU usage which was at a rediculous 25-45% now manages to hit 100% at times.

**Comment by chendrix** [comment]
Moved to concourse/concourse#1109
