### ISSUE TITLE
Concourse allows a numeric tag value to be uploaded in config, but can't use it when running tasks

### ISSUE THREAD

**Issue by geofffranks** [concourse/atc#89]
I'm using the `image_resource` attribute in my task, to define its docker image. I specified the `tag: 1.4` in my yaml. This appears to have been uploaded to concourse as a number, without causing any issues. However, when I tried to run the task, I get the below error about the tag being a number, and not a string.

I feel like this should either JustWork(tm), or error when `fly` uploads the config, indicating that the value needs to be a string. I'd prefer that it JustWork.

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
failed to read request: json: cannot unmarshal number into Go value of type string
```

**Comment by geofffranks** [comment]
Maybe this issue/fix belongs in the docker-image-resource repo instead?

**Comment by vito** [comment]
Yeah, this is an issue solely with the Docker image resource. You can also just open issues on `concourse/concourse`.

**Comment by vito** [comment]
consolidating this into https://github.com/concourse/docker-image-resource/issues/43
