### ISSUE TITLE
Limit a height of widget with logs content

### ISSUE THREAD

**Issue by DenisIzmaylov** [concourse/atc#90]
Sometimes we can get a lot of log lines in build process. For example `npm install` can produce up to "hundred of thousands" log lines. If we process build for a several images so our browser tab freezes.

![image](https://cloud.githubusercontent.com/assets/1690596/16506950/be97f446-3f2e-11e6-91a5-ed17a8b395dc.png)

It would be great:
1. Limit height of a log widget and make it possible to scroll it. Just do add the following styles:
   
   ```
   max-height: 500px;
   overflow-y: scroll;
   ```
2. Show only latests 500 lines and display all only by request (click on the button or scroll to up like in Slack).

**Comment by DenisIzmaylov** [comment]
Story: https://www.pivotaltracker.com/n/projects/1059262/stories/125980239

**Comment by vito** [comment]
That story only improves the time it takes to download the logs; if your browser was freezing up before when rendering the output, it still will, it'll just get there faster. :P

I like the idea of showing a limited number of log lines though and clicking it to expand the rest. Perhaps only if it exceeds a certain threshold?

**Comment by chendrix** [comment]
Moved to concourse/concourse#1110
